### ISSUE TITLE
0.5.0 cherry picks

### ISSUE THREAD

**Issue by mit-mit** [dartino/sdk#558]
We should pick the following for the 0.5.0 stable release:

 - [x] #557: unused import in volume.dart:
volume.dart change in https://github.com/dartino/sdk/commit/435ddbc7a0150dcffd7e31875e7a5a4c3fb35208
 - [x] #560: debugger fix
  https://github.com/dartino/sdk/commit/e483c95ad47f8ecdd1b8ff407ef657180785f414
 - [x] #553: Remove the dart:developer library from .platform files https://github.com/dartino/sdk/commit/ae63c0691c053a063d89054da0c90f4d1a86bff4
 - [x] #485: TCP socket and UDP support https://github.com/dartino/sdk/commit/3695591e838fc1c0be917178068899fe52bf0045
 - [x] Update documentation for gpio and nucleo_iks01a1 packages https://github.com/dartino/sdk/commit/2004f8c7e9b854a49f495a7f6a9933652a8365b4
 - [x] Disable analyze_samples tests on ARM https://github.com/dartino/sdk/commit/f23b21a19bfe0d6522e8fec5233f5ba3a539fb08
 - [x] skip analyze_tests on ARM https://github.com/dartino/sdk/commit/7733f32daaf893eb54dc5dde70223f315ac4f80b
 - [x] Revert "Use single precision transcendental functions on Cortex M" https://github.com/dartino/sdk/commit/4098c8f2fbc2d9403042fc7e25ad2f84d79a5e12
 - [x] Put status updates under the right headline https://github.com/dartino/sdk/commit/755f50cb1ff15009d692993b790d0b6bfa068244
 - [x] Fix parsing and handling of --no-wait to the build verb https://github.com/dartino/sdk/commit/f130ea46ef555cf99489f13596e2f4826907d815
 - [x] #565: Using the 'p' command in the debugger can crash the debugger https://github.com/dartino/sdk/commit/e830a0d37b60c8cb2b354ad74e40e043ce4046e6
 - [x] #567: No debugger feedback when 'b' command does not set a breakpoint https://github.com/dartino/sdk/commit/31c16beee2c2a8ec7e5beb6ecadecdf08edafa70
 - [x] Update .dartino-settings https://github.com/dartino/sdk/commit/d576e04e16aa06e1642180dd5d78aaeb9caa855e
 - [x] Add concurrency samples https://github.com/dartino/sdk/commit/8814b7582f453ccb9193eaa5e1223c9006754621
 - [x] Use /bin/cp to copy sparse files so they do not blow up https://github.com/dartino/sdk/commit/858ad886b1f1beb3dd8324be3273b6be8f6b09af
 - [x] #573 The STM32F7 UART device driver can get stuck sending https://github.com/dartino/sdk/commit/0e237c10809d626270c8148e4d1d790386f2b3f7
 - [x] #574: The dev release fails to download emul8 https://github.com/dartino/sdk/commit/c17478e5224cf2f03c735f70f87a7b9ef084ab9a
 - [x] #565: Use the actual frame for printing single values from the cli debugger https://github.com/dartino/sdk/commit/c477ef80343d5e6bd3452c93e12f7d21d55e2e2d

**Comment by sgjesse** [comment]
Version 0.5.0-dev.1.1 in https://github.com/dartino/sdk/commit/073336455adced76a6e1938c29313bf4fab58284

**Comment by sgjesse** [comment]
Version 0.5.0-dev.1.2 in https://github.com/dartino/sdk/commit/75d4490dea0fc24c702c1eed1e3c8fd71dce1f55

**Comment by sgjesse** [comment]
Version 0.5.0-dev.1.3 in https://github.com/dartino/sdk/commit/a8a9f2f3034b8fcf44bc40bd7d7a845b37b42cd5

**Comment by sgjesse** [comment]
Version 0.5.0-dev.1.4 in https://github.com/dartino/sdk/commit/f3f682bcd7dbb63f79cda087a1a8ce1476c65d52

**Comment by sgjesse** [comment]
Version 0.5.0-dev.1.5 in https://github.com/dartino/sdk/commit/5dfce8d8e48bc9b72c210e4e374d7fc87d486479

**Comment by sgjesse** [comment]
Version 0.5.0-dev.1.5 was released.
